Repository PKUHPC/OpenSCOW, pull requests merged in 2023-12, with the labels that each got.

#986 chore: 测试review bot
  .github/pkuhpc-review-bot.yml
Labels: Code-Approved, E2E-Approved, ReadyForMerge

#1033 fix(audit): 操作日志模糊搜索及操作类型和目标账户精确搜索报错修复
  .changeset/neat-beds-repair.md
  apps/audit-server/src/utils/operationLogs.ts
Labels: Code-Approved, E2E-Skipped, ReadyForMerge

#1034 fix(portal): 修复用户删除无权限目录时导致的崩溃问题
  .changeset/calm-ducks-rest.md
  apps/portal-server/src/utils/ssh.ts
  apps/portal-web/src/pages/api/file/deleteDir.ts
Labels: Code-Approved, E2E-Skipped, ReadyForMerge

#1041 fix(protal-web): 仪表盘信息面板title过长时折行问题和调整响应式样式
  .changeset/orange-hairs-trade.md
  apps/portal-web/src/pageComponents/dashboard/DoubleInfoPane.tsx
  apps/portal-web/src/pageComponents/dashboard/InfoPane.tsx
  apps/portal-web/src/pageComponents/dashboard/InfoPanes.tsx
Labels: Code-Approved, ReadyForMerge

#1042 fix(portal-web): 修改终端登录欢迎语过长会报错的提示
  .changeset/sharp-paws-hug.md
  apps/portal-web/src/i18n/en.ts
  apps/portal-web/src/i18n/zh_cn.ts
Labels: Code-Approved, ReadyForMerge

#825 feat(mis): 新增数据统计功能
  .changeset/gold-insects-trade.md
  .changeset/warm-islands-kneel.md
  apps/audit-server/package.json
  apps/audit-server/src/app.ts
  apps/audit-server/src/entities/OperationLog.ts
  apps/audit-server/src/services/operationLog.ts
  apps/audit-server/src/services/statistic.ts
  apps/audit-server/src/utils/operationLogs.ts
  apps/audit-server/tests/log/operationLogs.test.ts
  apps/audit-server/tests/statistic/statistic.test.ts
  apps/mis-server/src/entities/Account.ts
  apps/mis-server/src/entities/ChargeRecord.ts
  apps/mis-server/src/entities/PayRecord.ts
  apps/mis-server/src/entities/QueryCache.ts
  apps/mis-server/src/entities/index.ts
  apps/mis-server/src/migrations/.snapshot-scow_server.json
  apps/mis-server/src/migrations/Migration20231108022748.ts
  apps/mis-server/src/plugins/cachePlugin.ts
  apps/mis-server/src/plugins/index.ts
  apps/mis-server/src/services/admin.ts
  apps/mis-server/src/services/charging.ts
  apps/mis-server/src/services/job.ts
  apps/mis-server/src/services/user.ts
  apps/mis-server/src/utils/cache.ts
  apps/mis-server/tests/admin/getAdminInfo.test.ts
  apps/mis-server/tests/admin/user.test.ts
  apps/mis-server/tests/charging/statistics.test.ts
  apps/mis-server/tests/job/JobService.test.ts
  apps/mis-web/package.json
  apps/mis-web/src/apis/api.mock.ts
  apps/mis-web/src/apis/api.ts
  apps/mis-web/src/i18n/en.ts
  apps/mis-web/src/i18n/zh_cn.ts
  apps/mis-web/src/layouts/routes.tsx
  apps/mis-web/src/pageComponents/admin/DataBarChart.tsx
  apps/mis-web/src/pageComponents/admin/DataLineChart.tsx
  apps/mis-web/src/pageComponents/admin/StatisticCard.tsx
  apps/mis-web/src/pages/admin/statistic.tsx
  apps/mis-web/src/pages/api/admin/getActiveUserCount.ts
  apps/mis-web/src/pages/api/admin/getDailyCharge.ts
  apps/mis-web/src/pages/api/admin/getDailyPay.ts
  apps/mis-web/src/pages/api/admin/getJobTotalCount.ts
  apps/mis-web/src/pages/api/admin/getMisUsageCount.ts
  apps/mis-web/src/pages/api/admin/getNewJobCount.ts
  apps/mis-web/src/pages/api/admin/getNewUserCount.ts
  apps/mis-web/src/pages/api/admin/getPortalUsageCount.ts
  apps/mis-web/src/pages/api/admin/getStatisticInfo.ts
  apps/mis-web/src/pages/api/admin/getTopChargeAccount.ts
  apps/mis-web/src/pages/api/admin/getTopPayAccount.ts
  apps/mis-web/src/pages/api/admin/getTopSubmitJobUser.ts
  apps/mis-web/src/utils/client.ts
  apps/portal-server/src/utils/desktops.ts
  dev/vagrant/config/mis.yaml
  pnpm-lock.yaml
  protos/audit/statistic.proto
  protos/server/admin.proto
  protos/server/charging.proto
  protos/server/job.proto
  protos/server/user.proto
Labels: Code-Approved, E2E-Approved, ReadyForMerge

#1024 fix(portal): 优化从文件系统直接提交脚本任务
  .changeset/healthy-clocks-battle.md
  .changeset/wicked-wasps-matter.md
  apps/portal-server/src/services/job.ts
  apps/portal-web/src/i18n/en.ts
  apps/portal-web/src/i18n/zh_cn.ts
  apps/portal-web/src/pageComponents/filemanager/FileManager.tsx
  libs/protos/scheduler-adapter/package.json
Labels: Code-Approved, ReadyForMerge

#1048 chore: 更新日志中增加适配器接口版本要求部分
  scripts/version.mjs
Labels: Code-ReviewRequested

#1045 feat(ui): UI扩展功能
  .changeset/violet-walls-tease.md
  apps/mis-web/config.js
  apps/mis-web/config/mis.yaml
  apps/mis-web/src/layouts/BaseLayout.tsx
  apps/mis-web/src/pages/_app.tsx
  apps/mis-web/src/pages/extensions/[[...path]].tsx
  apps/mis-web/src/utils/config.ts
  apps/portal-web/config.js
  apps/portal-web/config/portal.yaml
  apps/portal-web/src/layouts/BaseLayout.tsx
  apps/portal-web/src/pages/_app.tsx
  apps/portal-web/src/pages/extensions/[[...path]].tsx
  apps/portal-web/src/utils/config.ts
  docs/docs/integration/index.md
  docs/docs/integration/integration.dio
  docs/docs/integration/integration.png
  docs/docs/integration/ui-extension/_category_.json
  docs/docs/integration/ui-extension/develop.md
  docs/docs/integration/ui-extension/extension.gif
  docs/docs/integration/ui-extension/ui-extension.md
  libs/config/src/mis.ts
  libs/config/src/portal.ts
  libs/web/package.json
  libs/web/src/extensions/ExtensionPage.tsx
  libs/web/src/extensions/UiExtensionStore.ts
  libs/web/src/extensions/manifests.ts
  libs/web/src/extensions/navigations.tsx
  libs/web/src/extensions/routes.ts
  libs/web/src/layouts/base/BaseLayout.tsx
  pnpm-lock.yaml
Labels: Code-ReviewRequested
