Repository PKUHPC/OpenSCOW, pull requests merged in 2024-02, with the labels that each got.

#1102 feat(portal): Web Shell支持跳转到文件编辑页面
  .changeset/twelve-boats-pretend.md
  apps/portal-server/assets/scow-shell-file.sh
  apps/portal-web/src/i18n/en.ts
  apps/portal-web/src/i18n/zh_cn.ts
  apps/portal-web/src/pageComponents/filemanager/FileManager.tsx
  apps/portal-web/src/pageComponents/shell/Shell.tsx
  apps/portal-web/src/pages/shell/[cluster]/[loginNode]/[[...path]].tsx
  docs/docs/deploy/config/portal/shell.md
Labels: Code-Approved, ReadyForMerge

#1108 fix(mis-server): 增加removeUserFromAccount测试用例
  apps/mis-server/tests/admin/user.test.ts
  dev/test-adapter/src/services/job.ts
Labels: Code-Approved, ReadyForMerge

#1111 docs: 增加SCOW AI Beta期间使用SCOW AI的配置文件指引
  docs/docs/deploy/config/ai/intro.md
Labels: Code-ReviewRequested

#1117 feat: 去掉创建用户/账户/租户或添加用户/白名单账户时手动输入的用户名的前后空格
  .changeset/strong-pumas-retire.md
  apps/mis-web/src/pageComponents/init/InitAdminForm.tsx
  apps/mis-web/src/pageComponents/tenant/AddWhitelistedAccountButton.tsx
  apps/mis-web/src/pageComponents/users/AddUserButton.tsx
  apps/mis-web/src/pageComponents/users/CreateUserModal.tsx
  apps/mis-web/src/pages/admin/tenants/create.tsx
  apps/mis-web/src/pages/tenant/accounts/create.tsx
  apps/mis-web/src/pages/tenant/users/create.tsx
Labels: Code-Approved, ReadyForMerge

#1110 feat(mis-web): 调整监控 iframe 高度自适应
  .changeset/chilled-cougars-protect.md
  apps/mis-web/src/pages/admin/monitor/resourceStatus.tsx
Labels: Code-Approved, ReadyForMerge

#1121 fix(lib-server): lib-server @scow/protos 从 devDependencies 移动到 dependencies
  .changeset/serious-starfishes-dance.md
  libs/server/package.json
  pnpm-lock.yaml
Labels: Code-Approved, ReadyForMerge

#1119 fix(docs): AI系统 （beta）配置介绍文档优化修改
  .changeset/mean-pianos-attend.md
  docs/docs/deploy/config/ai/intro.md
Labels: Code-Approved, ReadyForMerge

#1103 fix(portal-web): 修复目录下文件过多时 touch -a 会导致 500 报错的问题
  .changeset/angry-forks-promise.md
  apps/portal-server/src/services/file.ts
Labels: Code-Approved, ReadyForMerge

#1123 fix(ai): 修复模型版本编辑时名称重复校验问题
  .changeset/nine-ladybugs-own.md
  apps/ai/src/server/trpc/route/model/modelVersion.ts
Labels: Code-Approved, ReadyForMerge

#1132 fix(portal-web): dashboard的监控数据的clusterId
  .changeset/serious-llamas-approve.md
  apps/portal-web/src/pages/dashboard.tsx
Labels: Code-Approved, ReadyForMerge

#1130 fix(mis): 修复平台管理页面账户消费记录搜索账户名时传参错误问题
  .changeset/moody-camels-cheer.md
  apps/mis-web/src/pages/api/file/exportChargeRecord.ts
  apps/mis-web/src/pages/api/file/exportPayRecord.ts
  apps/mis-web/src/pages/api/finance/charges.ts
  apps/mis-web/src/pages/api/finance/getChargeRecordsTotalCount.ts
  apps/mis-web/src/pages/api/finance/payments.ts
Labels: Code-Approved, ReadyForMerge

#1135 fix: 使用外部认证系统时，外部系统未实现的功能在用户使用时提示用户功能未实现
  .changeset/heavy-flies-repair.md
  apps/auth/src/routes/changeEmail.ts
  apps/auth/src/routes/changePassword.ts
  apps/auth/src/routes/checkPassword.ts
  apps/auth/src/routes/createUser.ts
  apps/auth/src/routes/getUser.ts
  apps/mis-server/src/services/user.ts
  apps/mis-web/src/i18n/en.ts
  apps/mis-web/src/i18n/zh_cn.ts
  apps/mis-web/src/pageComponents/profile/ChangeEmailModal.tsx
  apps/mis-web/src/pageComponents/profile/ChangePasswordModal.tsx
  apps/mis-web/src/pages/admin/tenants/create.tsx
  apps/mis-web/src/pages/api/admin/changePassword.ts
  apps/mis-web/src/pages/api/profile/changeEmail.ts
  apps/mis-web/src/pages/api/profile/changePassword.ts
  apps/mis-web/src/pages/api/profile/checkPassword.ts
  apps/mis-web/src/pages/api/tenant/changePassword.ts
  apps/mis-web/src/pages/api/tenant/create.ts
  apps/portal-web/src/i18n/en.ts
  apps/portal-web/src/i18n/zh_cn.ts
  apps/portal-web/src/pageComponents/profile/ChangePasswordModal.tsx
  apps/portal-web/src/pages/api/profile/changePassword.ts
  apps/portal-web/src/pages/api/profile/checkPassword.ts
Labels: Code-Approved, ReadyForMerge

#1133 feat(portal): 只在使用文件传输功能时利用touch -a更新时间戳
  .changeset/great-jeans-obey.md
  .changeset/late-islands-mate.md
  apps/portal-server/src/services/file.ts
  apps/portal-web/src/pageComponents/filemanager/ClusterFileTable.tsx
  apps/portal-web/src/pages/api/file/list.ts
  protos/portal/file.proto
Labels: Code-Approved, ReadyForMerge

#1143 feat(mis-web): 集群和分区信息数据异步请求页面优化
  .changeset/eight-forks-sneeze.md
  apps/mis-web/src/i18n/en.ts
  apps/mis-web/src/i18n/zh_cn.ts
  apps/mis-web/src/pages/user/partitions.tsx
Labels: Code-Approved, ReadyForMerge

#1144 feat(mis-web): 初始化的用户管理新增前端搜索
  .changeset/brave-spiders-build.md
  apps/mis-web/src/i18n/en.ts
  apps/mis-web/src/i18n/zh_cn.ts
  apps/mis-web/src/pageComponents/init/InitUsersAndAccountsTable.tsx
Labels: Code-Approved, ReadyForMerge

#1070 feat: 操作日志优化
  .changeset/lovely-kings-taste.md
  .changeset/wet-teachers-fetch.md
  apps/audit-server/src/migrations/Migration20240218000000.ts
  apps/audit-server/tests/log/operationLogs.test.ts
  apps/audit-server/tests/statistic/statistic.test.ts
  apps/mis-web/src/components/OperationLogTable.tsx
  apps/mis-web/src/i18n/en.ts
  apps/mis-web/src/i18n/zh_cn.ts
  apps/mis-web/src/models/operationLog.ts
  apps/mis-web/src/pages/api/job/cancelJob.ts
  apps/mis-web/src/pages/api/job/changeJobTimeLimit.ts
  apps/portal-web/src/pages/api/app/createAppSession.ts
  apps/portal-web/src/pages/api/desktop/createDesktop.ts
  apps/portal-web/src/pages/api/desktop/killDesktop.ts
  apps/portal-web/src/pages/api/job/cancelJob.ts
  apps/portal-web/src/pages/api/job/deleteJobTemplate.ts
  apps/portal-web/src/pages/api/job/renameJobTemplate.ts
  apps/portal-web/src/pages/api/job/submitJob.ts
  protos/audit/operation_log.proto
Labels: Code-Approved, ReadyForMerge

#1146 fix(web): 去掉导航栏多余的下划线
  .changeset/famous-pots-act.md
  libs/web/src/layouts/base/common.tsx
Labels: Code-Approved, ReadyForMerge

#1147 fix(ai): 修复集群 partitions 为空时，页面崩溃的问题以及拼写错误
  .changeset/khaki-trees-kneel.md
  apps/ai/src/app/(auth)/jobs/[clusterId]/LaunchAppForm.tsx
  apps/ai/src/app/(auth)/jobs/[clusterId]/hooks.ts
Labels: Code-Approved, ReadyForMerge

#1101 feat(mis): 账户增加封锁阈值
  .changeset/mighty-countries-march.md
  .changeset/soft-countries-work.md
  apps/ai/src/models/operationLog.ts
  apps/audit-server/src/services/statistic.ts
  apps/mis-server/src/bl/charging.ts
  apps/mis-server/src/entities/Account.ts
  apps/mis-server/src/entities/Tenant.ts
  apps/mis-server/src/migrations/.snapshot-scow_server.json
  apps/mis-server/src/migrations/Migration20240204081801.ts
  apps/mis-server/src/services/account.ts
  apps/mis-server/src/services/export.ts
  apps/mis-server/src/services/tenant.ts
  apps/mis-server/tests/admin/getAccounts.test.ts
  apps/mis-server/tests/tenant/tenant.test.ts
  apps/mis-web/src/apis/api.mock.ts
  apps/mis-web/src/apis/api.ts
  apps/mis-web/src/i18n/en.ts
  apps/mis-web/src/i18n/zh_cn.ts
  apps/mis-web/src/models/UserSchemaModel.ts
  apps/mis-web/src/models/operationLog.ts
  apps/mis-web/src/pageComponents/accounts/AccountTable.tsx
  apps/mis-web/src/pageComponents/accounts/SetBlockThresholdAmountModal.tsx
  apps/mis-web/src/pageComponents/tenant/ChangeDefaultAccountBlockThresholdModal.tsx
  apps/mis-web/src/pages/accounts/[accountName]/info.tsx
  apps/mis-web/src/pages/api/admin/getAllAccounts.ts
  apps/mis-web/src/pages/api/file/exportAccount.ts
  apps/mis-web/src/pages/api/init/getAccounts.ts
  apps/mis-web/src/pages/api/tenant/getAccounts.ts
  apps/mis-web/src/pages/api/tenant/setBlockThreshold.ts
  apps/mis-web/src/pages/api/tenant/setDefaultAccountBlockThreshold.ts
  apps/mis-web/src/pages/tenant/info.tsx
  apps/portal-web/src/models/operationLog.ts
  libs/server/package.json
  protos/audit/operation_log.proto
  protos/server/account.proto
  protos/server/tenant.proto
Labels: Code-Approved, E2E-Approved, ReadyForMerge

#1141 feat(ai): k8s集群支持containerd运行时
  .changeset/six-wolves-pump.md
  .changeset/swift-geese-wait.md
  apps/ai/src/server/trpc/route/image/image.ts
  apps/ai/src/server/trpc/route/jobs/apps.ts
  apps/ai/src/server/utils/image.ts
  docs/docs/deploy/config/ai/intro.md
  libs/config/src/cluster.ts
Labels: Code-Approved, ReadyForMerge
