Repository PKUHPC/OpenSCOW, pull requests merged in 2024-07, with the labels that each got.

#1337 chore: 修复centos7包管理镜像地址
  dev/ldap/Dockerfile
Labels: Code-ReviewRequested

#1333 fix(web): 兼容低版本 chrome 浏览器，兼容 360 极速浏览器
  .changeset/tiny-ears-arrive.md
  apps/ai/src/app/clientLayout.tsx
  libs/web/package.json
  libs/web/src/layouts/AntdConfigProvider.tsx
  pnpm-lock.yaml
Labels: Code-Approved, ReadyForMerge

#1311 feat(web): UI扩展增加自定义导航栏链接
  .changeset/young-buttons-float.md
  apps/mis-web/src/layouts/BaseLayout.tsx
  apps/portal-web/src/layouts/BaseLayout.tsx
  docs/docs/integration/ui-extension/develop.md
  docs/docs/integration/ui-extension/extension.gif
  docs/src/components/HomepageFeatures.tsx
  libs/web/src/extensions/common.ts
  libs/web/src/extensions/manifests.ts
  libs/web/src/extensions/navbarLinks.tsx
  libs/web/src/extensions/navigations.tsx
  libs/web/src/extensions/routes.ts
  libs/web/src/layouts/base/BaseLayout.tsx
  libs/web/src/layouts/base/header/components.tsx
  libs/web/src/layouts/base/header/index.tsx
Labels: Code-ReviewRequested

#1339 fix(portal): 修复集群配置文件中loginNodes配置为字符串数组时报错问题
  .changeset/orange-beans-explain.md
  apps/mis-server/src/services/misConfig.ts
  apps/portal-server/tests/file/utils.ts
  apps/portal-web/config.js
  apps/portal-web/src/layouts/routes.tsx
  apps/portal-web/src/pages/api/getClusterConfigFiles.ts
  libs/config/src/cluster.ts
  libs/config/src/type.ts
  libs/server/src/typeConversion.ts
  libs/web/src/utils/typeConversion.ts
Labels: Code-Approved, ReadyForMerge

#1351 fix(web): 修复mis跳转portal失败的问题
  .changeset/neat-ants-invent.md
  apps/mis-web/src/layouts/BaseLayout.tsx
  apps/portal-web/src/layouts/BaseLayout.tsx
Labels: Code-Approved, ReadyForMerge

#1355 fix: 修复了header热区过小的问题
  .changeset/good-bags-grow.md
  libs/web/src/layouts/base/header/BigScreenMenu.tsx
Labels: Code-Approved, ReadyForMerge

#1352 fix(web): UI 扩展导航栏链接修改 href 为 path，行为和导航项的 path 保持一致
  .changeset/selfish-ravens-raise.md
  docs/docs/integration/ui-extension/develop.md
  libs/web/src/extensions/navbarLinks.tsx
  libs/web/src/layouts/base/BaseLayout.tsx
  libs/web/src/layouts/base/header/components.tsx
Labels: Code-ReviewRequested

#1356 fix: ai和hpc在提交作业和应用前检查一下是否重名
  .changeset/tasty-files-end.md
  apps/ai/src/server/trpc/route/jobs/apps.ts
  apps/ai/src/server/trpc/route/jobs/jobs.ts
  apps/portal-server/src/clusterops/app.ts
  apps/portal-server/src/services/job.ts
  apps/portal-web/src/pageComponents/app/LaunchAppForm.tsx
  apps/portal-web/src/pageComponents/job/SubmitJobForm.tsx
  apps/portal-web/src/pages/api/app/createAppSession.ts
  apps/portal-web/src/pages/api/job/submitJob.ts
Labels: Code-Approved, ReadyForMerge

#1359 revert: "fix: ai和hpc在提交作业和应用前检查一下是否重名"
  .changeset/tasty-files-end.md
  apps/ai/src/server/trpc/route/jobs/apps.ts
  apps/ai/src/server/trpc/route/jobs/jobs.ts
  apps/portal-server/src/clusterops/app.ts
  apps/portal-server/src/services/job.ts
  apps/portal-web/src/pageComponents/app/LaunchAppForm.tsx
  apps/portal-web/src/pageComponents/job/SubmitJobForm.tsx
  apps/portal-web/src/pages/api/app/createAppSession.ts
  apps/portal-web/src/pages/api/job/submitJob.ts
Labels: Code-ReviewRequested

#1347 fix(portal-server/mis-server): 启动时跳过已停用集群的ssh检查
  .changeset/twelve-olives-scream.md
  apps/mis-server/src/bl/PriceMap.ts
  apps/mis-server/src/bl/clustersUtils.ts
  apps/mis-server/src/plugins/clusters.ts
  apps/mis-server/src/services/init.ts
  apps/mis-server/src/services/misConfig.ts
  apps/mis-server/src/services/tenant.ts
  apps/mis-server/src/services/user.ts
  apps/mis-server/src/tasks/fetch.ts
  apps/mis-server/src/utils/createUser.ts
  apps/mis-web/src/pageComponents/admin/ClusterManagementTable.tsx
  apps/mis-web/src/utils/route.ts
  apps/portal-server/src/app.ts
  apps/portal-server/src/utils/proxy.ts
  apps/portal-server/src/utils/ssh.ts
  apps/portal-web/src/utils/route.ts
Labels: Code-Approved, E2E-Approved, ReadyForMerge

#1362 fix(portal-server): 修复获取 scowdClient 时拼接地址的错误
  .changeset/khaki-cheetahs-warn.md
  apps/portal-server/src/utils/scowd.ts
  libs/utils/src/url.ts
Labels: Code-Approved, ReadyForMerge

#1363 fix(web): 右上角nav在生成portal及mis的 a 标签时不添加base path
  .changeset/fast-kings-love.md
  apps/mis-web/src/layouts/BaseLayout.tsx
  apps/portal-web/src/layouts/BaseLayout.tsx
  libs/web/src/layouts/base/header/components.tsx
  libs/web/src/layouts/base/header/index.tsx
Labels: Code-Approved, ReadyForMerge

#1369 fix(ai): 区分SCOW和SCOW AI使用的有关适配器请求的公共逻辑函数
  apps/ai/src/server/trpc/route/jobs/apps.ts
  apps/ai/src/server/utils/schedulerAdapterUtils.ts
Labels: Code-Approved, ReadyForMerge

#1374 fix(mis): mis-server启动时，不完整同步一次封锁状态
  .changeset/ninety-zoos-think.md
  .changeset/shaggy-maps-hunt.md
  apps/mis-server/config/mis.yaml
  apps/mis-server/src/app.ts
  apps/mis-server/src/plugins/syncBlockStatus.ts
  apps/mis-server/src/services/admin.ts
  apps/mis-server/tests/admin/updateBlockStatus.test.ts
  apps/mis-web/src/i18n/en.ts
  apps/mis-web/src/i18n/zh_cn.ts
  apps/mis-web/src/pages/admin/systemDebug/slurmBlockStatus.tsx
  apps/mis-web/src/pages/api/admin/synchronize/syncBlockStatus.ts
  protos/server/admin.proto
Labels: Code-ReviewRequested

#1261 feat(ai): AI增加多机多卡 分布式训练
  .changeset/funny-peas-wave.md
  apps/ai/src/app/(auth)/jobs/[clusterId]/AppSessionsTable.tsx
  apps/ai/src/app/(auth)/jobs/[clusterId]/LaunchAppForm.tsx
  apps/ai/src/server/setup/jobShell.ts
  apps/ai/src/server/trpc/route/config.ts
  apps/ai/src/server/trpc/route/jobs/apps.ts
  apps/ai/src/server/trpc/route/jobs/index.ts
  apps/ai/src/server/trpc/route/jobs/jobs.ts
  apps/ai/src/server/utils/app.ts
  dev/vagrant/config/ai/apps/jupyter.yaml
  dev/vagrant/config/ai/apps/pycharm.yaml
  dev/vagrant/config/ai/apps/vscode.yaml
  libs/config/src/appForAi.ts
Labels: Code-ReviewRequested

#1377 fix(web): 如果UI扩展自定义导航栏接口返回的某个导航项的`path`与某个已有的路径的`clickToPath`相同（之前只检查`path`），则返回的路径也将不做进一步处理
  .changeset/tasty-geese-reflect.md
  docs/docs/integration/ui-extension/develop.md
  libs/web/src/extensions/navigations.tsx
Labels: Code-Approved, ReadyForMerge
