Repository PKUHPC/OpenSCOW, pull requests merged in 2024-01, with the labels that each got.

#1044 feat(mis-web): 管理系统新增集群监控功能
  .changeset/young-pants-occur.md
  apps/cli/assets/config/mis.yaml
  apps/mis-web/config.js
  apps/mis-web/package.json
  apps/mis-web/src/apis/api.mock.ts
  apps/mis-web/src/apis/api.ts
  apps/mis-web/src/i18n/en.ts
  apps/mis-web/src/i18n/zh_cn.ts
  apps/mis-web/src/layouts/routes.tsx
  apps/mis-web/src/pageComponents/admin/AllAlarmLogsTable.tsx
  apps/mis-web/src/pages/admin/monitor/alarmLog.tsx
  apps/mis-web/src/pages/admin/monitor/resourceStatus.tsx
  apps/mis-web/src/pages/api/admin/monitor/getAlarmDbId.ts
  apps/mis-web/src/pages/api/admin/monitor/getAlarmLogs.ts
  apps/mis-web/src/pages/api/admin/monitor/getAlarmLogsCount.ts
  apps/mis-web/src/pages/api/admin/monitor/getResourceStatus/[[...path]].ts
  apps/mis-web/src/utils/config.ts
  apps/mis-web/src/utils/constants.ts
  dev/vagrant/config/mis.yaml
  docs/docs/deploy/config/mis/cluster-monitor/alarmLog.png
  docs/docs/deploy/config/mis/cluster-monitor/index.md
  docs/docs/deploy/config/mis/cluster-monitor/resourceStatus.png
  docs/docs/hpccluster/cluster-monitor/alarmLog.png
  docs/docs/hpccluster/cluster-monitor/index.md
  docs/docs/hpccluster/cluster-monitor/resourceStatus.png
  libs/config/src/mis.ts
  pnpm-lock.yaml
Labels: Code-Approved, ReadyForMerge

#1036 chore(cli): cli 初始化配置文件分为简化版本和全版本
  .changeset/polite-turkeys-smile.md
  apps/cli/assets/init-full/config/apps/emacs.yaml
  apps/cli/assets/init-full/config/audit.yaml
  apps/cli/assets/init-full/config/auth.yml
  apps/cli/assets/init-full/config/clusterTexts.yaml
  apps/cli/assets/init-full/config/clusters/hpc01.yaml
  apps/cli/assets/init-full/config/common.yml
  apps/cli/assets/init-full/config/mis.yaml
  apps/cli/assets/init-full/config/portal.yaml
  apps/cli/assets/init-full/config/ui.yaml
  apps/cli/assets/init-full/fluent/fluent.conf
  apps/cli/assets/init-full/install.yaml
  apps/cli/assets/init-full/plugins/README.md
  apps/cli/assets/init-full/public/README.md
  apps/cli/assets/init/config/apps/emacs.yaml
  apps/cli/assets/init/config/audit.yaml
  apps/cli/assets/init/config/auth.yml
  apps/cli/assets/init/config/clusterTexts.yaml
  apps/cli/assets/init/config/clusters/hpc01.yaml
  apps/cli/assets/init/config/common.yaml
  apps/cli/assets/init/config/mis.yaml
  apps/cli/assets/init/config/portal.yaml
  apps/cli/assets/init/config/ui.yaml
  apps/cli/assets/init/fluent/fluent.conf
  apps/cli/assets/init/install.yaml
  apps/cli/assets/init/plugins/README.md
  apps/cli/assets/init/public/README.md
  apps/cli/src/cmd/init.ts
  apps/cli/src/index.ts
  apps/cli/tests/init.test.ts
  docs/docs/deploy/install/scow-cli.md
Labels: Code-Approved, ReadyForMerge

#1060 fix(mis): 增加对用户及账户关系的错误兼容，如果适配器的报错都是已存在，视为添加成功，如果都是不存在，视为移除成功
  .changeset/great-schools-guess.md
  apps/mis-server/src/services/user.ts
  apps/mis-server/src/utils/countSubstringOccurrences.ts
  apps/mis-web/src/pageComponents/users/UserTable.tsx
  apps/mis-web/src/pages/api/users/removeFromAccount.ts
Labels: Code-Approved, ReadyForMerge

#1061 fix(portal): 修复部分集群无法获取集群运行信息时导致仪表板无法展示其他正常信息
  .changeset/curly-seals-trade.md
  apps/portal-web/src/apis/api.ts
  apps/portal-web/src/i18n/en.ts
  apps/portal-web/src/i18n/zh_cn.ts
  apps/portal-web/src/pageComponents/dashboard/AddEntryModal.tsx
  apps/portal-web/src/pageComponents/dashboard/CardItem.tsx
  apps/portal-web/src/pageComponents/dashboard/InfoPanes.tsx
  apps/portal-web/src/pageComponents/dashboard/OverviewTable.tsx
  apps/portal-web/src/pageComponents/dashboard/Sortable.tsx
  apps/portal-web/src/pageComponents/dashboard/SortableItem.tsx
  apps/portal-web/src/pages/api/dashboard/getQuickEntries.ts
  apps/portal-web/src/pages/api/dashboard/saveQuickEntries.ts
  apps/portal-web/src/pages/dashboard.tsx
  apps/portal-web/src/utils/dashboard.ts
Labels: Code-Approved, ReadyForMerge

#1077 fix: 修复 codemirror 导致的崩溃问题
  .changeset/eighty-melons-dance.md
  apps/portal-web/package.json
  pnpm-lock.yaml
  renovate.json
Labels: Code-ReviewRequested

#1081 fix(cli): 添加 @sinclair/typebox 到 pkg
  .changeset/unlucky-zebras-design.md
  apps/cli/package.json
Labels: Code-ReviewRequested

#1075 feat(mis): 增加配置项控制普通用户是否可以修改作业时限
  .changeset/forty-ducks-hide.md
  .changeset/plenty-tools-flash.md
  apps/cli/assets/init-full/config/mis.yaml
  apps/mis-web/config.js
  apps/mis-web/src/pageComponents/job/RunningJobTable.tsx
  apps/mis-web/src/pages/api/job/cancelJob.ts
  apps/mis-web/src/pages/api/job/changeJobTimeLimit.ts
  apps/mis-web/src/pages/api/job/queryJobTimeLimit.ts
  apps/mis-web/src/server/jobAccessible.ts
  apps/mis-web/src/utils/config.ts
  dev/vagrant/config/mis.yaml
  libs/config/src/mis.ts
Labels: Code-Approved, ReadyForMerge

#1073 feat(mis): 新增管理系统添加用户至账户配置
  .changeset/thin-doors-tell.md
  .changeset/unlucky-llamas-serve.md
  apps/cli/assets/init-full/config/mis.yaml
  apps/mis-web/config.js
  apps/mis-web/src/pageComponents/users/AddUserButton.tsx
  apps/mis-web/src/pages/accounts/[accountName]/users.tsx
  apps/mis-web/src/pages/api/users/addToAccount.ts
  apps/mis-web/src/pages/api/users/create.ts
  apps/mis-web/src/utils/config.ts
  libs/config/src/mis.ts
Labels: Code-Approved, ReadyForMerge

#1092 fix: 修复turbo.json并更新turbo
  package.json
  pnpm-lock.yaml
  turbo.json
Labels: Code-ReviewRequested

#1093 fix: 修复renovate.json没有正确忽略一些包的更新
  renovate.json
Labels: Code-ReviewRequested

#1096 feat(mis-server): 适配 mikro-orm 更新导致的 Ref nullable 的默认值变化
  .changeset/five-dragons-deliver.md
  apps/mis-server/src/entities/StorageQuota.ts
  apps/mis-server/src/entities/UserAccount.ts
  apps/mis-server/src/migrations/.snapshot-scow_server.json
  apps/mis-server/src/migrations/Migration20240129075557.ts
Labels: Code-ReviewRequested

#1086 fix(portal-web): 修复文件管理列表连续双击文件名导致进入错误目录的问题
  .changeset/loud-fireants-jog.md
  apps/portal-web/src/pageComponents/filemanager/FileManager.tsx
Labels: Code-Approved, ReadyForMerge

#1095 fix(portal-web): 仪表盘处集群无法获取运行时不报500的错误提示和快捷方式跳转去掉basePath
  .changeset/tasty-walls-draw.md
  apps/portal-web/src/pageComponents/dashboard/OverviewTable.tsx
  apps/portal-web/src/pageComponents/dashboard/Sortable.tsx
  apps/portal-web/src/pages/dashboard.tsx
Labels: Code-Approved, ReadyForMerge

#1100 fix(portal-web): 修复连续双击文件名时 path 变化 loading 未变导致进入错误目录
  apps/portal-web/src/pageComponents/filemanager/FileManager.tsx
Labels: Code-Approved, ReadyForMerge

#1072 feat(mis): charge_record 表增加字段 user_id 及 metadata 以存储更多的信息
  .changeset/late-snakes-fold.md
  .changeset/loud-doors-rescue.md
  .changeset/nasty-garlics-help.md
  .changeset/slimy-bulldogs-allow.md
  apps/cli/assets/init-full/config/mis.yaml
  apps/mis-server/src/bl/charging.ts
  apps/mis-server/src/entities/ChargeRecord.ts
  apps/mis-server/src/migrations/.snapshot-scow_server.json
  apps/mis-server/src/migrations/Migration20240118021127.ts
  apps/mis-server/src/services/charging.ts
  apps/mis-server/src/services/export.ts
  apps/mis-server/src/services/job.ts
  apps/mis-server/src/tasks/fetch.ts
  apps/mis-server/src/utils/types.ts
  apps/mis-server/tests/charging/charging.test.ts
  apps/mis-server/tests/export/export.test.ts
  apps/mis-web/config.js
  apps/mis-web/src/i18n/en.ts
  apps/mis-web/src/i18n/zh_cn.ts
  apps/mis-web/src/pageComponents/finance/ChargeTable.tsx
  apps/mis-web/src/pages/api/file/exportChargeRecord.ts
  apps/mis-web/src/pages/api/finance/charges.ts
  apps/mis-web/src/pages/api/finance/getChargeRecordsTotalCount.ts
  apps/mis-web/src/utils/config.ts
  apps/mis-web/src/utils/metadata.ts
  dev/vagrant/config/mis.yaml
  docs/docs/deploy/config/customization/custom-config-i18n.md
  docs/docs/deploy/config/customization/custom-job-charge-metadata.md
  docs/docs/deploy/config/customization/custom-system-language.md
  docs/docs/deploy/config/customization/images/job-charge-metadata-cn.png
  docs/docs/deploy/config/customization/images/job-charge-metadata-en.png
  docs/docs/deploy/config/customization/images/job-charge-metadata-no-display.png
  libs/config/src/mis.ts
  libs/libconfig/src/parse.ts
  protos/server/charging.proto
  protos/server/export.proto
Labels: Code-Approved, E2E-Approved, ReadyForMerge

#1105 fix(mis-server): 修改cascade属性
  .changeset/two-readers-think.md
  apps/mis-server/src/entities/StorageQuota.ts
  apps/mis-server/src/entities/UserAccount.ts
Labels: Code-ReviewRequested
