Repository PKUHPC/OpenSCOW, pull requests merged in 2024-04, with the labels that each got.

#1191 fix(docs): 修改用户模型中账户状态及用户在账户中状态的文字描述错误
  .changeset/sharp-cycles-invent.md
  docs/docs/info/mis/business/users.md
Labels: Code-Approved, ReadyForMerge

#1189 fix(portal-web): 快捷方式的icon显示大小问题
  .changeset/tasty-beers-grow.md
  apps/portal-web/src/pageComponents/dashboard/EntryItem.tsx
Labels: Code-Approved, ReadyForMerge

#1194 feat(portal-web): 改进门户系统仪表盘各个模块的背景设计
  .changeset/wild-steaks-rescue.md
  apps/portal-web/src/pageComponents/dashboard/InfoPane.tsx
  apps/portal-web/src/pageComponents/dashboard/OverviewTable.tsx
Labels: Code-Approved, ReadyForMerge

#1192 fix(cli): 兼容旧版本自定义认证系统配置
  .changeset/olive-rivers-camp.md
  apps/cli/src/config/install.ts
Labels: Code-Approved, ReadyForMerge

#1197 chore: 暂停react-query更新
  renovate.json
Labels: Code-ReviewRequested

#1190 fix(ai): 修复jupyter启动时参数错误问题
  .changeset/little-snakes-camp.md
  apps/ai/config/ai/apps/jupter.yaml
  apps/ai/src/server/trpc/route/jobs/apps.ts
  dev/vagrant/config/ai/apps/jupyter.yaml
  docs/docs/deploy/config/ai/apps/apps/jupyterlab/index.md
Labels: Code-Approved, ReadyForMerge

#1182 feat(web): 优化适配器异常时的页面错误信息展示
  .changeset/tidy-ants-worry.md
  apps/mis-server/src/plugins/clusters.ts
  apps/mis-server/src/utils/error.ts
  apps/mis-web/src/i18n/en.ts
  apps/mis-web/src/i18n/index.ts
  apps/mis-web/src/i18n/zh_cn.ts
  apps/mis-web/src/pageComponents/users/UserTable.tsx
  apps/mis-web/src/pages/_app.tsx
  apps/mis-web/src/pages/api/admin/fetchJobs/fetchJobs.ts
  apps/mis-web/src/pages/api/admin/getClusterUsers.ts
  apps/mis-web/src/pages/api/job/changeJobTimeLimit.ts
  apps/mis-web/src/pages/api/job/getAvailableBillingTable.ts
  apps/mis-web/src/pages/api/job/getBillingItems.ts
  apps/mis-web/src/pages/api/job/getMissingDefaultPriceItems.ts
  apps/mis-web/src/pages/api/job/queryJobTimeLimit.ts
  apps/mis-web/src/pages/api/job/runningJobs.ts
  apps/mis-web/src/pages/api/users/addToAccount.ts
  apps/mis-web/src/utils/route.ts
  apps/portal-server/src/clusterops/app.ts
  apps/portal-server/src/services/config.ts
  apps/portal-server/src/services/job.ts
  apps/portal-server/src/utils/clusters.ts
  apps/portal-web/src/i18n/en.ts
  apps/portal-web/src/i18n/index.ts
  apps/portal-web/src/i18n/zh_cn.ts
  apps/portal-web/src/pageComponents/filemanager/FileManager.tsx
  apps/portal-web/src/pageComponents/job/AccountSelector.tsx
  apps/portal-web/src/pageComponents/job/RunningJobTable.tsx
  apps/portal-web/src/pageComponents/job/SubmitJobForm.tsx
  apps/portal-web/src/pages/_app.tsx
  apps/portal-web/src/pages/api/app/getAppSessions.ts
  apps/portal-web/src/pages/api/cluster.ts
  apps/portal-web/src/pages/api/job/getAccounts.ts
  apps/portal-web/src/pages/api/job/getAllJobs.ts
  apps/portal-web/src/pages/api/job/getRunningJobs.ts
  apps/portal-web/src/utils/route.ts
  libs/server/src/scheduleAdapter.ts
  libs/web/src/utils/libWebI18n/libI18n.ts
Labels: Code-Approved, E2E-Approved, ReadyForMerge

#1195 feat(mis): 账户白名单、账户消费记录下都支持以用户ID和姓名搜索
  .changeset/eleven-garlics-prove.md
  apps/mis-web/src/i18n/en.ts
  apps/mis-web/src/i18n/zh_cn.ts
  apps/mis-web/src/pageComponents/finance/ChargeTable.tsx
  apps/mis-web/src/pageComponents/tenant/AccountWhitelistTable.tsx
Labels: Code-Approved, ReadyForMerge

#1209 chore: 更新CI配置
  .github/workflows/docs-preview.yaml
  .github/workflows/docs.yaml
  .github/workflows/pr-cleanup.yaml
  .github/workflows/side-projects.yaml
  .github/workflows/test-build-publish.yaml
Labels: Code-ReviewRequested

#1214 fix(ci): 修改pnpm最新版升级到9.0造成的构建问题
  dev/test-adapter/Dockerfile
  docker/Dockerfile.docs
  docker/Dockerfile.scow
Labels: Code-ReviewRequested

#1206 feat(mis): 管理系统平台数据统计作业提交用户前十数横坐标改为userName
  .changeset/great-carrots-refuse.md
  apps/mis-server/src/services/job.ts
  apps/mis-server/tests/job/JobService.test.ts
  apps/mis-web/src/apis/api.mock.ts
  apps/mis-web/src/apis/api.ts
  apps/mis-web/src/pages/admin/statistic.tsx
  apps/mis-web/src/pages/api/admin/getUsersWithMostJobSubmissions.ts
  protos/server/job.proto
Labels: Code-Approved, ReadyForMerge

#1215 feat(web): 支持多个UI扩展
  .changeset/giant-dolphins-vanish.md
  apps/mis-web/src/layouts/BaseLayout.tsx
  apps/mis-web/src/pages/_app.tsx
  apps/mis-web/src/pages/dashboard.tsx
  apps/mis-web/src/pages/extensions/[[...path]].tsx
  apps/mis-web/src/utils/config.ts
  apps/mis-web/src/utils/head.ts
  apps/portal-web/config/portal.yaml
  apps/portal-web/src/layouts/BaseLayout.tsx
  apps/portal-web/src/pages/_app.tsx
  apps/portal-web/src/pages/extensions/[[...path]].tsx
  apps/portal-web/src/utils/config.ts
  apps/portal-web/src/utils/head.ts
  apps/portal-web/tsconfig.json
  docs/docs/integration/ui-extension/develop.md
  docs/docs/integration/ui-extension/ui-extension.md
  libs/config/src/mis.ts
  libs/config/src/portal.ts
  libs/config/src/uiExtensions.ts
  libs/web/src/components/head.tsx
  libs/web/src/extensions/ExtensionPage.tsx
  libs/web/src/extensions/UiExtensionStore.ts
  libs/web/src/extensions/navigations.tsx
  libs/web/src/layouts/base/BaseLayout.tsx
Labels: Code-ReviewRequested

#1218 fix(ai): 启用serverMinification，使用--no-mangling
  .changeset/serious-fishes-bathe.md
  apps/ai/next.config.mjs
  apps/ai/package.json
Labels: Code-ReviewRequested

#1202 feat(ai): ai 增加vnc， shell 到容器， ai提交作业优化
  .changeset/lemon-fans-peel.md
  .changeset/pretty-toes-greet.md
  .changeset/witty-camels-share.md
  apps/ai/assets/app/vnc_entry.sh
  apps/ai/next.config.mjs
  apps/ai/package.json
  apps/ai/src/app/(auth)/dashboard/page.tsx
  apps/ai/src/app/(auth)/jobShell/[clusterId]/[jobId]/page.tsx
  apps/ai/src/app/(auth)/jobs/[clusterId]/AppSessionsTable.tsx
  apps/ai/src/app/(auth)/jobs/[clusterId]/ConnectToAppLink.tsx
  apps/ai/src/app/(auth)/jobs/[clusterId]/LaunchAppForm.tsx
  apps/ai/src/components/shell/JobShell.tsx
  apps/ai/src/pages/api/setup.ts
  apps/ai/src/server/config/env.ts
  apps/ai/src/server/setup/jobShell.ts
  apps/ai/src/server/trpc/route/config.ts
  apps/ai/src/server/trpc/route/jobs/apps.ts
  apps/ai/src/server/trpc/route/jobs/jobs.ts
  apps/ai/src/server/utils/app.ts
  apps/ai/src/utils/vnc.ts
  apps/cli/src/compose/index.ts
  dev/test-adapter/src/services/app.ts
  dev/vagrant/config/ai/apps/jupyter.yaml
  dev/vagrant/config/ai/apps/pycharm.yaml
  docs/docs/deploy/config/ai/apps/configure-vnc-app.md
  docs/docs/deploy/config/ai/apps/intro.md
  docs/docs/deploy/config/ai/intro.md
  libs/config/src/appForAi.ts
  libs/config/src/cluster.ts
  libs/protos/scheduler-adapter/package.json
  pnpm-lock.yaml
Labels: Code-Approved, E2E-Approved, ReadyForMerge

#1222 chore: 固定 github workflow 中 ifaxity/wait-on-action的版本
  .github/workflows/test-build-publish.yaml
Labels: Code-ReviewRequested

#1224 ci: PR增加API breaking change检查
  .github/workflows/api-breaking.yaml
  package.json
Labels: Code-ReviewRequested

#1230 feat(hook): 支持配置多个Hook
  .changeset/violet-deers-sniff.md
  docs/docs/integration/scow-api-hook/hook.md
  libs/config/src/common.ts
  libs/hook/src/index.ts
Labels: Code-ReviewRequested
