Repository PKUHPC/OpenSCOW, pull requests merged in 2024-03, with the labels that each got.

#1137 fix(portal-web): 改进门户快捷方式的UI
  .changeset/spotty-onions-notice.md
  apps/portal-web/public/public/apps/VSCode.svg
  apps/portal-web/src/apis/api.mock.ts
  apps/portal-web/src/components/Icon.tsx
  apps/portal-web/src/pageComponents/dashboard/AddEntryModal.tsx
  apps/portal-web/src/pageComponents/dashboard/CardItem.tsx
  apps/portal-web/src/pageComponents/dashboard/ChangeClusterModal.tsx
  apps/portal-web/src/pageComponents/dashboard/DashboardSection.tsx
  apps/portal-web/src/pageComponents/dashboard/EntryItem.tsx
  apps/portal-web/src/pageComponents/dashboard/QuickEntry.tsx
  apps/portal-web/src/pageComponents/dashboard/Sortable.tsx
  apps/portal-web/src/pageComponents/dashboard/SortableItem.tsx
  apps/portal-web/src/pages/dashboard.tsx
  apps/portal-web/src/utils/dashboard.ts
Labels: Code-ReviewRequested

#1153 fix(portal-web): 仪表盘cpu和gpu利用率百分比显示错误
  .changeset/little-apricots-mix.md
  apps/portal-web/src/pages/dashboard.tsx
Labels: Code-Approved, ReadyForMerge

#1154 fix(web): 修复 token 失效后切换系统不跳转回登录页面的问题
  .changeset/blue-ears-provide.md
  apps/mis-web/src/pages/api/auth/callback.ts
  apps/mis-web/src/stores/UserStore.ts
  apps/portal-web/src/pages/api/auth/callback.ts
  apps/portal-web/src/stores/UserStore.ts
Labels: Code-Approved, ReadyForMerge

#1163 fix(mis-web): 修改租户管理下用户列表中可用账户的列名
  .changeset/hungry-rats-mix.md
  apps/mis-web/src/i18n/en.ts
  apps/mis-web/src/i18n/zh_cn.ts
Labels: Code-Approved, ReadyForMerge

#1162 fix(cli): 去掉 node-cron 表达式前秒的限制
  .changeset/wild-paws-drop.md
  apps/cli/assets/init-full/config/mis.yaml
  apps/cli/assets/init/config/mis.yaml
  deploy/vagrant/scow/scow-deployment/config/mis.yaml
  docs/blog/2023-10-20-scow-update1.0.md
  docs/docs/deploy/config/mis/intro.md
Labels: Code-Approved, ReadyForMerge

#1160 fix(mis-server): 修复导出账户和导出充值记录接口缺失limit，offset过滤的问题
  .changeset/tidy-boxes-study.md
  apps/mis-server/src/services/export.ts
Labels: Code-Approved, ReadyForMerge

#1159 style: 修复拼写错误
  apps/audit-server/src/services/statistic.ts
  apps/mis-server/src/services/charging.ts
  apps/mis-server/src/services/job.ts
  apps/mis-server/src/services/user.ts
  libs/server/src/date.ts
Labels: Code-Approved, ReadyForMerge

#1164 fix(shell): 修复文件管理下在终端中打开连接失败问题
  .changeset/swift-papayas-draw.md
  apps/portal-web/src/pageComponents/filemanager/FileManager.tsx
  apps/portal-web/src/pages/shell/[cluster]/[loginNode]/[[...path]].tsx
Labels: Code-Approved, ReadyForMerge

#1171 fix(portal): 修改 GetFileMetadataResponse 中文件大小 size 为 uint64
  .changeset/kind-nails-hunt.md
  protos/portal/file.proto
Labels: Code-Approved, ReadyForMerge

#1172 chore: 修复ai中创建或复制数据时检查文件路径源，后台日志没有打印
  .changeset/purple-crews-march.md
  apps/ai/src/server/utils/checkPathPermission.ts
Labels: Code-Approved, ReadyForMerge

#1174 fix(ai): 修改 checkpermission 函数对于命令执行错误时的判断逻辑
  .changeset/light-hornets-grow.md
  apps/ai/src/server/utils/checkPathPermission.ts
Labels: Code-Approved, ReadyForMerge

#1176 fix(ai): 修复 AI 训练 coreCount 在 gpu 下传参错误问题
  .changeset/ten-flies-notice.md
  apps/ai/src/app/(auth)/jobs/[clusterId]/LaunchAppForm.tsx
Labels: Code-Approved, ReadyForMerge

#1161 feat(mis): 账户状态调整
  .changeset/nasty-turtles-grin.md
  .changeset/tender-bees-provide.md
  apps/mis-server/src/bl/block.ts
  apps/mis-server/src/bl/charging.ts
  apps/mis-server/src/bl/importUsers.ts
  apps/mis-server/src/entities/Account.ts
  apps/mis-server/src/migrations/.snapshot-scow_server.json
  apps/mis-server/src/migrations/Migration20240304064259.ts
  apps/mis-server/src/services/account.ts
  apps/mis-server/src/services/export.ts
  apps/mis-server/src/services/tenant.ts
  apps/mis-server/src/services/user.ts
  apps/mis-server/src/utils/accountUserState.ts
  apps/mis-server/tests/admin/createAccount.test.ts
  apps/mis-server/tests/admin/getAccounts.test.ts
  apps/mis-server/tests/admin/getAdminInfo.test.ts
  apps/mis-server/tests/admin/importUsers.test.ts
  apps/mis-server/tests/admin/user.test.ts
  apps/mis-server/tests/admin/whitelist.test.ts
  apps/mis-server/tests/charging/charging.test.ts
  apps/mis-server/tests/charging/statistics.test.ts
  apps/mis-server/tests/data/data.ts
  apps/mis-server/tests/export/export.test.ts
  apps/mis-web/src/apis/api.mock.ts
  apps/mis-web/src/i18n/en.ts
  apps/mis-web/src/i18n/zh_cn.ts
  apps/mis-web/src/models/User.ts
  apps/mis-web/src/models/UserSchemaModel.ts
  apps/mis-web/src/pageComponents/accounts/AccountTable.tsx
  apps/mis-web/src/pageComponents/init/InitUsersAndAccountsTable.tsx
  apps/mis-web/src/pages/accounts/[accountName]/info.tsx
  apps/mis-web/src/pages/api/admin/getAllAccounts.ts
  apps/mis-web/src/pages/api/file/exportAccount.ts
  apps/mis-web/src/pages/api/tenant/getAccounts.ts
  apps/mis-web/src/pages/api/tenant/setBlockThreshold.ts
  apps/mis-web/src/pages/profile/index.tsx
  docs/docs/info/mis/business/account_state_explanation.png
  docs/docs/info/mis/business/account_state_explanation_without_frozen.png
  docs/docs/info/mis/business/users.md
  protos/server/account.proto
  protos/server/export.proto
Labels: Code-Approved, E2E-Approved, ReadyForMerge

#1181 fix(ai): Containerd运行时下大镜像推送失败
  .changeset/cuddly-frogs-rest.md
  apps/ai/src/app/(auth)/image/CreateEditImageModal.tsx
  apps/ai/src/server/trpc/route/image/image.ts
  apps/ai/src/server/utils/image.ts
Labels: Code-Approved, ReadyForMerge

#1170 feat(mis): 用户封锁和限额操作优化
  .changeset/fluffy-eagles-chew.md
  .changeset/weak-flies-fly.md
  apps/mis-server/src/bl/block.ts
  apps/mis-server/src/bl/charging.ts
  apps/mis-server/src/bl/importUsers.ts
  apps/mis-server/src/entities/UserAccount.ts
  apps/mis-server/src/migrations/.snapshot-scow_server.json
  apps/mis-server/src/migrations/Migration20240314075417.ts
  apps/mis-server/src/migrations/Migration20240328071020.ts
  apps/mis-server/src/services/account.ts
  apps/mis-server/src/services/export.ts
  apps/mis-server/src/services/jobChargeLimit.ts
  apps/mis-server/src/services/user.ts
  apps/mis-server/src/utils/accountUserState.ts
  apps/mis-server/tests/admin/getAccounts.test.ts
  apps/mis-server/tests/admin/importUsers.test.ts
  apps/mis-server/tests/admin/jobChargeLimit.test.ts
  apps/mis-server/tests/admin/user.test.ts
  apps/mis-server/tests/data/data.ts
  apps/mis-server/tests/export/export.test.ts
  apps/mis-server/tests/job/fetchJobs.test.ts
  apps/mis-web/src/i18n/en.ts
  apps/mis-web/src/i18n/zh_cn.ts
  apps/mis-web/src/models/User.ts
  apps/mis-web/src/models/UserSchemaModel.ts
  apps/mis-web/src/pageComponents/users/JobChargeLimitModal.tsx
  apps/mis-web/src/pageComponents/users/UserTable.tsx
  apps/mis-web/src/pages/api/users/jobChargeLimit/set.ts
  docs/docs/info/mis/business/user_state_in_account_explanation.png
  docs/docs/info/mis/business/users.md
  libs/web/src/utils/form.ts
  libs/web/src/utils/libWebI18n/libWebEn.ts
  libs/web/src/utils/libWebI18n/libWebZhCn.ts
  protos/server/account.proto
  protos/server/user.proto
Labels: Code-Approved, E2E-Approved, ReadyForMerge
